---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
- name: pcf-pipelines
- name: version
- name: fly

outputs:
- name: pcf-pipelines-release-tarball
- name: pivnet-metadata

params:
  AVAILABILITY: Admins Only

run:
  path: pcf-pipelines/ci/tasks/create-release/task.sh
