---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs
 
inputs:
- name: tarball

outputs:
- name: unpacked_tarball

run:
 path: sh
 args:
 - -c
 - |
   tar -C unpacked_tarball -xf tarball/*.tgz
