# Ciphers
# An ordered, colon-delimited list of Golang supported TLS cipher suites in OpenSSL format.
# Operators should verify that these are supported by any clients or downstream components that will initiate TLS handshakes with the Router/HAProxy.
# The recommended settings are filled in below, change as necessary.
router_tls_ciphers: "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384"
haproxy_tls_ciphers: "DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384"

# C2C Networking network CIDR
container_networking_nw_cidr: 10.255.0.0/16

# For credhub integration, replace dummy values in the following structure
# and set the number of credhub instances in resource config to 2
credhub_encryption_keys: |
  - name: dummy encryption key 1
    key:
      secret: CHANGEME_CHANGEME_CHANGEME_CHANGEME
    primary: true
  - name: encryption key 2
    key:
      secret: CHANGEME_CHANGEME_CHANGEME_CHANGEME

# DB Creds
# Usernames must be 16 characters or fewer
db_accountdb_password: CHANGEME
db_accountdb_username: CHANGEME
db_app_usage_service_password: CHANGEME
db_app_usage_service_username: CHANGEME
db_autoscale_password: CHANGEME
db_autoscale_username: CHANGEME
db_ccdb_password: CHANGEME
db_ccdb_username: CHANGEME
db_diego_password: CHANGEME
db_diego_username: CHANGEME
db_locket_password: CHANGEME
db_locket_username: CHANGEME
db_networkpolicyserverdb_password: CHANGEME
db_networkpolicyserverdb_username: CHANGEME
db_nfsvolumedb_password: CHANGEME
db_nfsvolumedb_username: CHANGEME
db_notifications_password: CHANGEME
db_notifications_username: CHANGEME
db_routing_password: CHANGEME
db_routing_username: CHANGEME
db_silk_password: CHANGEME
db_silk_username: CHANGEME
db_uaa_password: CHANGEME
db_uaa_username: CHANGEME

# Errands to disable prior to deploying ERT
# Valid values:
#   all
#   none
#   "" (empty string)
#   Any combination of the following, separated by comma:
#     smoke-tests
#     push-apps-manager
#     notifications
#     notifications-ui
#     push-pivotal-account
#     autoscaling
#     autoscaling-register-broker
#     nfsbrokerpush
ert_errands_to_disable: none

# PCF Elastic Runtime minor version to track
ert_major_minor_version: ^1\.12\..*$

# GCP project to create the infrastructure in
gcp_project_id: CHANGEME

# GCP region
gcp_region: us-central1

# Identifier to prepend to GCP infrastructure names/labels; this should be globally unique
gcp_resource_prefix: CHANGEME

# GCP credentials JSON. The service account must have the Editor role.
gcp_service_account_key: |
  CHANGEME

# GCP Interopable storage access key: https://console.cloud.google.com/storage/settings
gcp_storage_access_key: CHANGEME
gcp_storage_secret_key: CHANGEME

# Storage Location
gcp_storage_bucket_location: US

# GCP Zones
gcp_zone_1: us-central1-a
gcp_zone_2: us-central1-b
gcp_zone_3: us-central1-c

# Optional - if your git repo requires an SSH key.
git_private_key:

# Required if haproxy_forward_tls is enabled - HAProxy will use the CA provided to verify the certificates provided by the router.
haproxy_backend_ca:

# If enabled HAProxy will forward all requests to the router over TLS (enable|disable)
haproxy_forward_tls: enable

# Whether or not the ERT VMs are internet connected.
internet_connected: false

# Whether to enable MySQL backups. (disable|s3|scp)
mysql_backups: disable

#S3 backup config params (leave empty values if you're not using s3)
mysql_backups_s3_access_key_id:
mysql_backups_s3_bucket_name:
mysql_backups_s3_bucket_path:
mysql_backups_s3_cron_schedule:
mysql_backups_s3_endpoint_url:
mysql_backups_s3_secret_access_key:

#SCP backup config params (leave empty values if you're not using scp)
mysql_backups_scp_cron_schedule:
mysql_backups_scp_destination:
mysql_backups_scp_key:
mysql_backups_scp_port:
mysql_backups_scp_server:
mysql_backups_scp_user:

# Email address for sending mysql monitor notifications
mysql_monitor_recipient_email:  CHANGEME

# Optional. If using own certs, follow this format (if
# blank the cert will be auto generated):
networking_poe_ssl_certs:
#networking_poe_ssl_certs: |
#  - name: Point of Entry Certificate 1
#    certificate:
#      cert_pem: |
#        -----BEGIN EXAMPLE CERTIFICATE-----
#        ...
#        -----END EXAMPLE CERTIFICATE-----
#      private_key_pem: |
#        -----BEGIN EXAMPLE CERTIFICATE-----
#        ...
#        -----END EXAMPLE CERTIFICATE-----
#  - name: PoE certificate 2
#    certificate:
#      cert_pem: |
#        -----BEGIN EXAMPLE CERTIFICATE-----
#        ...
#        -----END EXAMPLE CERTIFICATE-----
#      private_key_pem: |
#        -----BEGIN EXAMPLE RSA PRIVATE KEY-----
#        ...
#        -----END EXAMPLE RSA PRIVATE KEY-----

# Operations Manager credentials to set
# Either opsman_client_id/opsman_client_secret or opsman_admin_username/opsman_admin_password needs to be specified
opsman_admin_password: CHANGEME
opsman_admin_username: CHANGEME
opsman_client_id: CHANGEME
opsman_client_secret: CHANGEME

# This should be your pcf_ert_domain with "opsman." as a prefix
opsman_domain_or_ip_address: CHANGEME

# PCF Ops Manager minor version to track
opsman_major_minor_version: ^1\.12\..*$

# Optional PEM-encoded certificates to add to BOSH director
opsman_trusted_certs: |

# Elastic Runtime Domain
pcf_ert_domain: CHANGEME # This is the top level domain that ERT apps and services will be accessible with
                         # e.g.: if the apps domain is apps.pcf.example.org then pcf_ert_domain should be pcf.example.org

# Pivnet token for downloading resources from Pivnet. Find this token at https://network.pivotal.io/users/dashboard/edit-profile
pivnet_token: CHANGEME

# Optional - these certificates can be used to validate the certificates from incoming client requests.
# All CA certificates should be appended together into a single collection of PEM-encoded entries.
routing_custom_ca_certificates:

# Disable HTTP on gorouters (true|false)
routing_disable_http: false

# Support for the X-Forwarded-Client-Cert header. Possible values: (load_balancer|ha_proxy|router)
routing_tls_termination: load_balancer

# Setting appropriate Application Security Groups is critical for a secure
# deployment. Change the value of the param below to "X" to acknowledge that
# once the Elastic Runtime deployment completes, you will review and set the
# appropriate application security groups.
# See https://docs.pivotal.io/pivotalcf/opsguide/app-sec-groups.html
security_acknowledgement: CHANGEME

terraform_statefile_bucket: CHANGEME
