---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/rootfs}

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_CLIENT_ID: con-client
  OPSMAN_CLIENT_SECRET: mypassword
  PIVNET_API_TOKEN:
  NO_PROXY:
  OM_IP:
  IAAS:

inputs:
  - name: pivnet-product
  - name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/upload-product-and-stemcell/task.sh
